export const IS_LOADING = 'IS_LOADING'
export const SET_MODAL = 'SET_MODAL'

// AUTH
export const SET_USER = 'SET_USER'
export const IS_LOADING_REGISTER = 'IS_LOADING_REGISTER'
export const IS_LOADING_LOGIN = 'IS_LOADING_LOGIN'

// <-- MODAL -->
export const CREATE_MODAL = 'CREATE_MODAL'
export const EDIT_MODAL = 'EDIT_MODAL'
export const DETAIL_ACTIVE = 'DETAIL_ACTIVE'
export const MODAL_DETAIL = 'MODAL_DETAIL'

// USER LIST
export const SET_USER_LISTS = 'SET_USER_LISTS'
export const SET_PER_PAGE_USER_LISTS = 'SET_PER_PAGE_USER_LISTS'

// QUIZ LIST
export const SET_QUIZ_LISTS = 'SET_QUIZ_LISTS'
export const SET_PER_PAGE_QUIZ_LISTS = 'SET_PER_PAGE_QUIZ_LISTS'
export const SET_QUIZ_INDEX = 'SET_QUIZ_INDEX'
export const IS_LOADING_TRY_QUIZ = 'IS_LOADING_TRY_QUIZ'
export const SET_TRY_QUIZ_LISTS = 'SET_TRY_QUIZ_LISTS'
export const IS_LOADING_ANSWER_QUIZ = 'IS_LOADING_ANSWER_QUIZ'
export const COUNT_ANSWER_QUIZ = 'COUNT_ANSWER_QUIZ'
